#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

db_name=$(ynh_app_setting_get "$app" db_name)
final_path=$(ynh_app_setting_get $app final_path)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

# Remove a service from the admin panel, added by `yunohost service add`
if yunohost service status "$app" >/dev/null 2>&1
then
	ynh_print_info "Removing $app service"
	yunohost service remove "$app"
fi
#=================================================
# STOP AND REMOVE SERVICE
#=================================================

ynh_remove_systemd_config

#=================================================
# REMOVE THE MySQL DATABASE
#=================================================

# Remove a database if it exists, along with the associated user
ynh_mysql_remove_db "$db_name" "$app"

#=================================================
# REMOVE DEPENDENCIES
#=================================================

# Remove metapackage and its dependencies
ynh_remove_app_dependencies

#=================================================
# REMOVE APP MAIN DIR
#=================================================

# Remove the app directory securely
ynh_secure_remove "$final_path"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================

# Remove the dedicated nginx config
ynh_remove_nginx_config

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================

# Remove the app-specific logrotate config
ynh_remove_logrotate

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE uwsgi and systemd files
#=================================================

# Remove the uwsgi file
ynh_secure_remove "/etc/uwsgi/apps-available/$app.ini"

# Remove the log files
ynh_secure_remove "/var/log/$app/"

#=================================================
# GENERIC FINALIZATION
#=================================================
# REMOVE DEDICATED USER
#=================================================

# Delete a system user
ynh_system_user_delete "$app"
