#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

db_name=$(ynh_app_setting_get "$app" db_name)

#=================================================
# REMOVE THE Service
#=================================================

ynh_remove_systemd_config



#=================================================
# REMOVE THE MySQL DATABASE
#=================================================

# Remove a database if it exists, along with the associated user
ynh_mysql_remove_db "$db_name" "$app"

#=================================================
# REMOVE DEPENDENCIES
#=================================================

# Remove metapackage and its dependencies
ynh_remove_app_dependencies

#=================================================
# REMOVE APP MAIN DIR
#=================================================

# Remove the app directory securely
ynh_secure_remove "/var/www/$app"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================

# Remove the dedicated nginx config
ynh_remove_nginx_config

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================

# Remove the app-specific logrotate config
ynh_remove_logrotate

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE uwsgi and systemd files
#=================================================

ynh_secure_remove "/etc/systemd/system/$app.service"

#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

# Remove a service from the admin panel, added by `yunohost service add`
if yunohost service status "$app" >/dev/null 2>&1
then
	yunohost service remove "$app"
fi

#=================================================
# GENERIC FINALIZATION
#=================================================
# REMOVE DEDICATED USER
#=================================================

# Delete a system user
ynh_system_user_delete "$app"
